# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6454c6dd0c14b2a6a0fb25e8a263bea5fd8a4078735e2d30a3e8219be9148f4587a8cef71dc45c4686889f9c20f2b13d3365dad585a745f957af744c1d634c

test:
  secret_key_base: b99af10710b703080c6904c573899608f21b782e4299d2e29ab8148088865c2327ffac0033a2113721d4c4d84e6c6422bd2ce9da61cf33d096f3be822b5a5c11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
